// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class OpenApiCommonModelMessages {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static OpenApiCommonModelMessages() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiBPcGVuQXBpQ29tbW9uTW9kZWxNZXNzYWdlcy5wcm90bypJChBQcm90b1Bh", 
          "eWxvYWRUeXBlEhEKDVBST1RPX01FU1NBR0UQBRINCglFUlJPUl9SRVMQMhIT", 
          "Cg9IRUFSVEJFQVRfRVZFTlQQMyrwAQoOUHJvdG9FcnJvckNvZGUSEQoNVU5L", 
          "Tk9XTl9FUlJPUhABEhcKE1VOU1VQUE9SVEVEX01FU1NBR0UQAhITCg9JTlZB", 
          "TElEX1JFUVVFU1QQAxIRCg1USU1FT1VUX0VSUk9SEAUSFAoQRU5USVRZX05P", 
          "VF9GT1VORBAGEhYKEkNBTlRfUk9VVEVfUkVRVUVTVBAHEhIKDkZSQU1FX1RP", 
          "T19MT05HEAgSEQoNTUFSS0VUX0NMT1NFRBAJEhsKF0NPTkNVUlJFTlRfTU9E", 
          "SUZJQ0FUSU9OEAoSGAoUQkxPQ0tFRF9QQVlMT0FEX1RZUEUQC0JNCihjb20u", 
          "eHRyYWRlci5wcm90b2NvbC5wcm90by5jb21tb25zLm1vZGVsQhxDb250YWlu", 
        "ZXJDb21tb25Nb2RlbE1lc3NhZ2VzUAGgAQE="));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Enums
public enum ProtoPayloadType {
  PROTO_MESSAGE = 5,
  ERROR_RES = 50,
  HEARTBEAT_EVENT = 51,
}

public enum ProtoErrorCode {
  UNKNOWN_ERROR = 1,
  UNSUPPORTED_MESSAGE = 2,
  INVALID_REQUEST = 3,
  TIMEOUT_ERROR = 5,
  ENTITY_NOT_FOUND = 6,
  CANT_ROUTE_REQUEST = 7,
  FRAME_TOO_LONG = 8,
  MARKET_CLOSED = 9,
  CONCURRENT_MODIFICATION = 10,
  BLOCKED_PAYLOAD_TYPE = 11,
}

#endregion


#endregion Designer generated code
