// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class Openapicommonmessages {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_ProtoMessage__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::ProtoMessage, global::ProtoMessage.Builder> internal__static_ProtoMessage__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_ProtoErrorRes__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::ProtoErrorRes, global::ProtoErrorRes.Builder> internal__static_ProtoErrorRes__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_ProtoHeartbeatEvent__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::ProtoHeartbeatEvent, global::ProtoHeartbeatEvent.Builder> internal__static_ProtoHeartbeatEvent__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static Openapicommonmessages() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtvcGVuYXBpY29tbW9ubWVzc2FnZXMucHJvdG8aIE9wZW5BcGlDb21tb25N", 
          "b2RlbE1lc3NhZ2VzLnByb3RvIkkKDFByb3RvTWVzc2FnZRITCgtwYXlsb2Fk", 
          "VHlwZRgBIAIoDRIPCgdwYXlsb2FkGAIgASgMEhMKC2NsaWVudE1zZ0lkGAMg", 
          "ASgJIosBCg1Qcm90b0Vycm9yUmVzEjEKC3BheWxvYWRUeXBlGAEgASgOMhEu", 
          "UHJvdG9QYXlsb2FkVHlwZToJRVJST1JfUkVTEhEKCWVycm9yQ29kZRgCIAIo", 
          "CRITCgtkZXNjcmlwdGlvbhgDIAEoCRIfChdtYWludGVuYW5jZUVuZFRpbWVz", 
          "dGFtcBgEIAEoBCJOChNQcm90b0hlYXJ0YmVhdEV2ZW50EjcKC3BheWxvYWRU", 
          "eXBlGAEgASgOMhEuUHJvdG9QYXlsb2FkVHlwZToPSEVBUlRCRUFUX0VWRU5U", 
          "QkIKImNvbS54dHJhZGVyLnByb3RvY29sLnByb3RvLmNvbW1vbnNCF0NvbnRh", 
        "aW5lckNvbW1vbk1lc3NhZ2VzUAGgAQE="));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_ProtoMessage__Descriptor = Descriptor.MessageTypes[0];
      internal__static_ProtoMessage__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::ProtoMessage, global::ProtoMessage.Builder>(internal__static_ProtoMessage__Descriptor,
              new string[] { "PayloadType", "Payload", "ClientMsgId", });
      internal__static_ProtoErrorRes__Descriptor = Descriptor.MessageTypes[1];
      internal__static_ProtoErrorRes__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::ProtoErrorRes, global::ProtoErrorRes.Builder>(internal__static_ProtoErrorRes__Descriptor,
              new string[] { "PayloadType", "ErrorCode", "Description", "MaintenanceEndTimestamp", });
      internal__static_ProtoHeartbeatEvent__Descriptor = Descriptor.MessageTypes[2];
      internal__static_ProtoHeartbeatEvent__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::ProtoHeartbeatEvent, global::ProtoHeartbeatEvent.Builder>(internal__static_ProtoHeartbeatEvent__Descriptor,
              new string[] { "PayloadType", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        global::OpenApiCommonModelMessages.Descriptor, 
        }, assigner);
  }
  #endregion
  
}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class ProtoMessage : pb::GeneratedMessage<ProtoMessage, ProtoMessage.Builder> {
  private ProtoMessage() { }
  private static readonly ProtoMessage defaultInstance = new ProtoMessage().MakeReadOnly();
  private static readonly string[] _protoMessageFieldNames = new string[] { "clientMsgId", "payload", "payloadType" };
  private static readonly uint[] _protoMessageFieldTags = new uint[] { 26, 18, 8 };
  public static ProtoMessage DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override ProtoMessage DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override ProtoMessage ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::Openapicommonmessages.internal__static_ProtoMessage__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<ProtoMessage, ProtoMessage.Builder> InternalFieldAccessors {
    get { return global::Openapicommonmessages.internal__static_ProtoMessage__FieldAccessorTable; }
  }
  
  public const int PayloadTypeFieldNumber = 1;
  private bool hasPayloadType;
  private uint payloadType_;
  public bool HasPayloadType {
    get { return hasPayloadType; }
  }
  [global::System.CLSCompliant(false)]
  public uint PayloadType {
    get { return payloadType_; }
  }
  
  public const int PayloadFieldNumber = 2;
  private bool hasPayload;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  public bool HasPayload {
    get { return hasPayload; }
  }
  public pb::ByteString Payload {
    get { return payload_; }
  }
  
  public const int ClientMsgIdFieldNumber = 3;
  private bool hasClientMsgId;
  private string clientMsgId_ = "";
  public bool HasClientMsgId {
    get { return hasClientMsgId; }
  }
  public string ClientMsgId {
    get { return clientMsgId_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasPayloadType) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _protoMessageFieldNames;
    if (hasPayloadType) {
      output.WriteUInt32(1, field_names[2], PayloadType);
    }
    if (hasPayload) {
      output.WriteBytes(2, field_names[1], Payload);
    }
    if (hasClientMsgId) {
      output.WriteString(3, field_names[0], ClientMsgId);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasPayloadType) {
      size += pb::CodedOutputStream.ComputeUInt32Size(1, PayloadType);
    }
    if (hasPayload) {
      size += pb::CodedOutputStream.ComputeBytesSize(2, Payload);
    }
    if (hasClientMsgId) {
      size += pb::CodedOutputStream.ComputeStringSize(3, ClientMsgId);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static ProtoMessage ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ProtoMessage ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ProtoMessage ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ProtoMessage ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ProtoMessage ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ProtoMessage ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static ProtoMessage ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static ProtoMessage ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static ProtoMessage ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ProtoMessage ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private ProtoMessage MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(ProtoMessage prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<ProtoMessage, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(ProtoMessage cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private ProtoMessage result;
    
    private ProtoMessage PrepareBuilder() {
      if (resultIsReadOnly) {
        ProtoMessage original = result;
        result = new ProtoMessage();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override ProtoMessage MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::ProtoMessage.Descriptor; }
    }
    
    public override ProtoMessage DefaultInstanceForType {
      get { return global::ProtoMessage.DefaultInstance; }
    }
    
    public override ProtoMessage BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is ProtoMessage) {
        return MergeFrom((ProtoMessage) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(ProtoMessage other) {
      if (other == global::ProtoMessage.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasPayloadType) {
        PayloadType = other.PayloadType;
      }
      if (other.HasPayload) {
        Payload = other.Payload;
      }
      if (other.HasClientMsgId) {
        ClientMsgId = other.ClientMsgId;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_protoMessageFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _protoMessageFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            result.hasPayloadType = input.ReadUInt32(ref result.payloadType_);
            break;
          }
          case 18: {
            result.hasPayload = input.ReadBytes(ref result.payload_);
            break;
          }
          case 26: {
            result.hasClientMsgId = input.ReadString(ref result.clientMsgId_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasPayloadType {
      get { return result.hasPayloadType; }
    }
    [global::System.CLSCompliant(false)]
    public uint PayloadType {
      get { return result.PayloadType; }
      set { SetPayloadType(value); }
    }
    [global::System.CLSCompliant(false)]
    public Builder SetPayloadType(uint value) {
      PrepareBuilder();
      result.hasPayloadType = true;
      result.payloadType_ = value;
      return this;
    }
    public Builder ClearPayloadType() {
      PrepareBuilder();
      result.hasPayloadType = false;
      result.payloadType_ = 0;
      return this;
    }
    
    public bool HasPayload {
      get { return result.hasPayload; }
    }
    public pb::ByteString Payload {
      get { return result.Payload; }
      set { SetPayload(value); }
    }
    public Builder SetPayload(pb::ByteString value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasPayload = true;
      result.payload_ = value;
      return this;
    }
    public Builder ClearPayload() {
      PrepareBuilder();
      result.hasPayload = false;
      result.payload_ = pb::ByteString.Empty;
      return this;
    }
    
    public bool HasClientMsgId {
      get { return result.hasClientMsgId; }
    }
    public string ClientMsgId {
      get { return result.ClientMsgId; }
      set { SetClientMsgId(value); }
    }
    public Builder SetClientMsgId(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasClientMsgId = true;
      result.clientMsgId_ = value;
      return this;
    }
    public Builder ClearClientMsgId() {
      PrepareBuilder();
      result.hasClientMsgId = false;
      result.clientMsgId_ = "";
      return this;
    }
  }
  static ProtoMessage() {
    object.ReferenceEquals(global::Openapicommonmessages.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class ProtoErrorRes : pb::GeneratedMessage<ProtoErrorRes, ProtoErrorRes.Builder> {
  private ProtoErrorRes() { }
  private static readonly ProtoErrorRes defaultInstance = new ProtoErrorRes().MakeReadOnly();
  private static readonly string[] _protoErrorResFieldNames = new string[] { "description", "errorCode", "maintenanceEndTimestamp", "payloadType" };
  private static readonly uint[] _protoErrorResFieldTags = new uint[] { 26, 18, 32, 8 };
  public static ProtoErrorRes DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override ProtoErrorRes DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override ProtoErrorRes ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::Openapicommonmessages.internal__static_ProtoErrorRes__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<ProtoErrorRes, ProtoErrorRes.Builder> InternalFieldAccessors {
    get { return global::Openapicommonmessages.internal__static_ProtoErrorRes__FieldAccessorTable; }
  }
  
  public const int PayloadTypeFieldNumber = 1;
  private bool hasPayloadType;
  private global::ProtoPayloadType payloadType_ = global::ProtoPayloadType.ERROR_RES;
  public bool HasPayloadType {
    get { return hasPayloadType; }
  }
  public global::ProtoPayloadType PayloadType {
    get { return payloadType_; }
  }
  
  public const int ErrorCodeFieldNumber = 2;
  private bool hasErrorCode;
  private string errorCode_ = "";
  public bool HasErrorCode {
    get { return hasErrorCode; }
  }
  public string ErrorCode {
    get { return errorCode_; }
  }
  
  public const int DescriptionFieldNumber = 3;
  private bool hasDescription;
  private string description_ = "";
  public bool HasDescription {
    get { return hasDescription; }
  }
  public string Description {
    get { return description_; }
  }
  
  public const int MaintenanceEndTimestampFieldNumber = 4;
  private bool hasMaintenanceEndTimestamp;
  private ulong maintenanceEndTimestamp_;
  public bool HasMaintenanceEndTimestamp {
    get { return hasMaintenanceEndTimestamp; }
  }
  [global::System.CLSCompliant(false)]
  public ulong MaintenanceEndTimestamp {
    get { return maintenanceEndTimestamp_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasErrorCode) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _protoErrorResFieldNames;
    if (hasPayloadType) {
      output.WriteEnum(1, field_names[3], (int) PayloadType, PayloadType);
    }
    if (hasErrorCode) {
      output.WriteString(2, field_names[1], ErrorCode);
    }
    if (hasDescription) {
      output.WriteString(3, field_names[0], Description);
    }
    if (hasMaintenanceEndTimestamp) {
      output.WriteUInt64(4, field_names[2], MaintenanceEndTimestamp);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasPayloadType) {
      size += pb::CodedOutputStream.ComputeEnumSize(1, (int) PayloadType);
    }
    if (hasErrorCode) {
      size += pb::CodedOutputStream.ComputeStringSize(2, ErrorCode);
    }
    if (hasDescription) {
      size += pb::CodedOutputStream.ComputeStringSize(3, Description);
    }
    if (hasMaintenanceEndTimestamp) {
      size += pb::CodedOutputStream.ComputeUInt64Size(4, MaintenanceEndTimestamp);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static ProtoErrorRes ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static ProtoErrorRes ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static ProtoErrorRes ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ProtoErrorRes ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private ProtoErrorRes MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(ProtoErrorRes prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<ProtoErrorRes, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(ProtoErrorRes cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private ProtoErrorRes result;
    
    private ProtoErrorRes PrepareBuilder() {
      if (resultIsReadOnly) {
        ProtoErrorRes original = result;
        result = new ProtoErrorRes();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override ProtoErrorRes MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::ProtoErrorRes.Descriptor; }
    }
    
    public override ProtoErrorRes DefaultInstanceForType {
      get { return global::ProtoErrorRes.DefaultInstance; }
    }
    
    public override ProtoErrorRes BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is ProtoErrorRes) {
        return MergeFrom((ProtoErrorRes) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(ProtoErrorRes other) {
      if (other == global::ProtoErrorRes.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasPayloadType) {
        PayloadType = other.PayloadType;
      }
      if (other.HasErrorCode) {
        ErrorCode = other.ErrorCode;
      }
      if (other.HasDescription) {
        Description = other.Description;
      }
      if (other.HasMaintenanceEndTimestamp) {
        MaintenanceEndTimestamp = other.MaintenanceEndTimestamp;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_protoErrorResFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _protoErrorResFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            object unknown;
            if(input.ReadEnum(ref result.payloadType_, out unknown)) {
              result.hasPayloadType = true;
            } else if(unknown is int) {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              unknownFields.MergeVarintField(1, (ulong)(int)unknown);
            }
            break;
          }
          case 18: {
            result.hasErrorCode = input.ReadString(ref result.errorCode_);
            break;
          }
          case 26: {
            result.hasDescription = input.ReadString(ref result.description_);
            break;
          }
          case 32: {
            result.hasMaintenanceEndTimestamp = input.ReadUInt64(ref result.maintenanceEndTimestamp_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasPayloadType {
     get { return result.hasPayloadType; }
    }
    public global::ProtoPayloadType PayloadType {
      get { return result.PayloadType; }
      set { SetPayloadType(value); }
    }
    public Builder SetPayloadType(global::ProtoPayloadType value) {
      PrepareBuilder();
      result.hasPayloadType = true;
      result.payloadType_ = value;
      return this;
    }
    public Builder ClearPayloadType() {
      PrepareBuilder();
      result.hasPayloadType = false;
      result.payloadType_ = global::ProtoPayloadType.ERROR_RES;
      return this;
    }
    
    public bool HasErrorCode {
      get { return result.hasErrorCode; }
    }
    public string ErrorCode {
      get { return result.ErrorCode; }
      set { SetErrorCode(value); }
    }
    public Builder SetErrorCode(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasErrorCode = true;
      result.errorCode_ = value;
      return this;
    }
    public Builder ClearErrorCode() {
      PrepareBuilder();
      result.hasErrorCode = false;
      result.errorCode_ = "";
      return this;
    }
    
    public bool HasDescription {
      get { return result.hasDescription; }
    }
    public string Description {
      get { return result.Description; }
      set { SetDescription(value); }
    }
    public Builder SetDescription(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasDescription = true;
      result.description_ = value;
      return this;
    }
    public Builder ClearDescription() {
      PrepareBuilder();
      result.hasDescription = false;
      result.description_ = "";
      return this;
    }
    
    public bool HasMaintenanceEndTimestamp {
      get { return result.hasMaintenanceEndTimestamp; }
    }
    [global::System.CLSCompliant(false)]
    public ulong MaintenanceEndTimestamp {
      get { return result.MaintenanceEndTimestamp; }
      set { SetMaintenanceEndTimestamp(value); }
    }
    [global::System.CLSCompliant(false)]
    public Builder SetMaintenanceEndTimestamp(ulong value) {
      PrepareBuilder();
      result.hasMaintenanceEndTimestamp = true;
      result.maintenanceEndTimestamp_ = value;
      return this;
    }
    public Builder ClearMaintenanceEndTimestamp() {
      PrepareBuilder();
      result.hasMaintenanceEndTimestamp = false;
      result.maintenanceEndTimestamp_ = 0UL;
      return this;
    }
  }
  static ProtoErrorRes() {
    object.ReferenceEquals(global::Openapicommonmessages.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class ProtoHeartbeatEvent : pb::GeneratedMessage<ProtoHeartbeatEvent, ProtoHeartbeatEvent.Builder> {
  private ProtoHeartbeatEvent() { }
  private static readonly ProtoHeartbeatEvent defaultInstance = new ProtoHeartbeatEvent().MakeReadOnly();
  private static readonly string[] _protoHeartbeatEventFieldNames = new string[] { "payloadType" };
  private static readonly uint[] _protoHeartbeatEventFieldTags = new uint[] { 8 };
  public static ProtoHeartbeatEvent DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override ProtoHeartbeatEvent DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override ProtoHeartbeatEvent ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::Openapicommonmessages.internal__static_ProtoHeartbeatEvent__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<ProtoHeartbeatEvent, ProtoHeartbeatEvent.Builder> InternalFieldAccessors {
    get { return global::Openapicommonmessages.internal__static_ProtoHeartbeatEvent__FieldAccessorTable; }
  }
  
  public const int PayloadTypeFieldNumber = 1;
  private bool hasPayloadType;
  private global::ProtoPayloadType payloadType_ = global::ProtoPayloadType.HEARTBEAT_EVENT;
  public bool HasPayloadType {
    get { return hasPayloadType; }
  }
  public global::ProtoPayloadType PayloadType {
    get { return payloadType_; }
  }
  
  public override bool IsInitialized {
    get {
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _protoHeartbeatEventFieldNames;
    if (hasPayloadType) {
      output.WriteEnum(1, field_names[0], (int) PayloadType, PayloadType);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasPayloadType) {
      size += pb::CodedOutputStream.ComputeEnumSize(1, (int) PayloadType);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static ProtoHeartbeatEvent ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ProtoHeartbeatEvent ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private ProtoHeartbeatEvent MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(ProtoHeartbeatEvent prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<ProtoHeartbeatEvent, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(ProtoHeartbeatEvent cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private ProtoHeartbeatEvent result;
    
    private ProtoHeartbeatEvent PrepareBuilder() {
      if (resultIsReadOnly) {
        ProtoHeartbeatEvent original = result;
        result = new ProtoHeartbeatEvent();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override ProtoHeartbeatEvent MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::ProtoHeartbeatEvent.Descriptor; }
    }
    
    public override ProtoHeartbeatEvent DefaultInstanceForType {
      get { return global::ProtoHeartbeatEvent.DefaultInstance; }
    }
    
    public override ProtoHeartbeatEvent BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is ProtoHeartbeatEvent) {
        return MergeFrom((ProtoHeartbeatEvent) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(ProtoHeartbeatEvent other) {
      if (other == global::ProtoHeartbeatEvent.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasPayloadType) {
        PayloadType = other.PayloadType;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_protoHeartbeatEventFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _protoHeartbeatEventFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            object unknown;
            if(input.ReadEnum(ref result.payloadType_, out unknown)) {
              result.hasPayloadType = true;
            } else if(unknown is int) {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              unknownFields.MergeVarintField(1, (ulong)(int)unknown);
            }
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasPayloadType {
     get { return result.hasPayloadType; }
    }
    public global::ProtoPayloadType PayloadType {
      get { return result.PayloadType; }
      set { SetPayloadType(value); }
    }
    public Builder SetPayloadType(global::ProtoPayloadType value) {
      PrepareBuilder();
      result.hasPayloadType = true;
      result.payloadType_ = value;
      return this;
    }
    public Builder ClearPayloadType() {
      PrepareBuilder();
      result.hasPayloadType = false;
      result.payloadType_ = global::ProtoPayloadType.HEARTBEAT_EVENT;
      return this;
    }
  }
  static ProtoHeartbeatEvent() {
    object.ReferenceEquals(global::Openapicommonmessages.Descriptor, null);
  }
}

#endregion


#endregion Designer generated code
